name: Run Scraper

on: push

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
        with:
          ref: action
          repository: Heyctoi/Heyctoi.github.io
          token: ${{ secrets.TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
          
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installing all necessary packages
        run: |
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay dateparser
          choco install googlechrome --ignore-checksums  # Install Chrome via Chocolatey
          
      - name: Running the Python script scraper
        run: python scraper/main.py

      - name: Running the Python script ICS
        run: python ics/ics.py
        
